stages:
  - build
  - test

image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build into public folder:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - public


test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html


